

<<<<<<< HEAD
jobs:
  firstjob:
    runs_on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Welcome Message
        run: echo "This is my first GitHub Actions workflow!"
      - name: List Files
        run: ls
      - name: Read File
        run: cat README.md
=======
>>>>>>> 59c91895c42d6b122f3ffc409f7ad41ccf3fa2b4
